# SPIKE — can a service be *installed at runtime* as a podman pod,
# and does that pod behave as a member of the promoter chain?
#
# The question behind it: we want `briardctl service install` to put a service on a node with
# no OS switch. Today the payload's systemd unit is generated by NixOS at build time, which is
# what bakes the data mount into its ExecStart — the one genuinely baked thing left. Quadlet is
# podman's own systemd generator: it turns files under /run/containers/systemd into real units at
# `daemon-reload`, i.e. it moves unit generation from build time to runtime. If that works here,
# the baked-mount problem dissolves rather than needing a workaround, and multi-container services
# (Immich is four containers) become a pod rather than a redesign.
#
# It boots the SHIPPED guest — no payload — and installs a two-container pod onto it, which is
# exactly the gesture. What it is deliberately NOT: installing onto an already-promoted node
# (that needs the maintenance bracket) or any manifest/catalog machinery. Mechanism only.
#
# Runs under the `debug` tag: it answers a design question, and is either promoted into the real
# real test or deleted once it has.
{ pkgs, guestModule }:

let
  h = import ./lib.nix { inherit pkgs guestModule; };

  # Two distinct images so the pod is genuinely multi-container. A serves and persists (the
  # existing fixture); B is a probe that proves both shared properties at once — it reaches A
  # over localhost (one network namespace) and writes its verdict into its own directory under
  # the SAME service subvolume (one rollback unit).
  imgA = pkgs.dockerTools.buildImage {
    name = "briard-spike-a";
    tag = "v0";
    config.Cmd = [ "${pkgs.dummy-service}/bin/dummy-service" ];
  };
  imgB = pkgs.dockerTools.buildImage {
    name = "briard-spike-b";
    tag = "v0";
    copyToRoot = pkgs.buildEnv {
      name = "spike-b-root";
      paths = [ pkgs.busybox pkgs.curl ];
    };
    config.Cmd = [
      "/bin/sh"
      "-c"
      # Its peer is on localhost only if they share a netns.
      "while true; do curl -fsS http://127.0.0.1:8080/healthz >/data/peer 2>/dev/null || echo unreachable >/data/peer; sleep 1; done"
    ];
  };

  # The quadlet source files. In production `briardctl` renders these from the service manifest;
  # here they stand in for that output, so the spike tests the mechanism and not our renderer.
  # No [Install] section on purpose: nothing may auto-start, because the promoter decides.
  quadletUnits = pkgs.runCommand "quadlet-spike-units" { } ''
    mkdir -p $out
    cat > $out/spikepod.pod <<'EOF'
    [Pod]
    PodName=briard-spike
    Network=host
    EOF
    cat > $out/spike-a.container <<'EOF'
    [Container]
    Image=briard-spike-a:v0
    Pod=spikepod.pod
    Volume=/var/lib/briard/spike/a:/var/lib/briard/dummy
    EOF
    cat > $out/spike-b.container <<'EOF'
    [Container]
    Image=briard-spike-b:v0
    Pod=spikepod.pod
    Volume=/var/lib/briard/spike/b:/data
    EOF
  '';

  # The service's data as ONE subvolume with a per-container subdirectory inside it — the shape
  # what layer 1 requires, and the only shape the existing rollback verbs can handle:
  # `data.restore` does `btrfs subvolume delete`, which REFUSES on a subvolume containing nested
  # subvolumes. So per-container storage must be plain directories, never nested subvolumes.
  # In production this is what the install step creates once (it replicates with the volume);
  # here it is a chain member so the ordering is real.
  spikeData = {
    description = "Spike: the service's data subvolume (one subvolume, per-container subdirs)";
    wantedBy = [ ];
    after = [ "briard-data.service" ];
    requires = [ "briard-data.service" ];
    path = [ pkgs.btrfs-progs pkgs.coreutils ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = pkgs.writeShellScript "spike-data-up" ''
        set -eu
        btrfs subvolume show /var/lib/briard/spike >/dev/null 2>&1 \
          || btrfs subvolume create /var/lib/briard/spike
        mkdir -p /var/lib/briard/spike/a /var/lib/briard/spike/b
      '';
    };
  };

  resource = h.mkResource [
    { name = "node1"; id = 0; }
    { name = "node2"; id = 1; }
    { name = "witness"; id = 2; diskless = true; }
  ];
  # Promoter = false: the test writes the snippet itself, which is what the agent does in
  # production and what makes "the chain names a unit quadlet generated" a real assertion.
  diskNode = { config, ... }: {
    imports = [ (h.mkNode { inherit resource; promoter = false; }) ];
    # R1 needs NO integration, which the spike found the hard way (an explicit
    # systemd.generators entry collided with an existing one): the podman package ships
    # lib/systemd/system-generators/podman-system-generator, and `virtualisation.podman.enable`
    # -- which is already on so a zero-service node still has a container runtime --
    # pulls it in via systemd.packages. Quadlet is therefore ALREADY live in the shipped guest.
    systemd.services.briard-spike-data = spikeData;
    environment.systemPackages = [ pkgs.btrfs-progs ]; # test-only: the snapshot assertion (R6)
  };
  witnessNode = h.mkNode { inherit resource; diskless = true; promoter = false; };
in
pkgs.testers.runNixOSTest {
  name = "quadlet-spike";
  skipTypeCheck = true;

  nodes = {
    node1 = diskNode;
    node2 = diskNode;
    witness = witnessNode;
  };

  testScript = ''
    disk_nodes = [node1, node2]
    machines = [node1, node2, witness]
    start_all()
    for m in machines:
        m.wait_for_unit("multi-user.target")
        m.succeed("modprobe drbd")
    for m in disk_nodes:
        m.succeed("drbdadm create-md --force r0")
    for m in machines:
        m.succeed("systemctl start drbd@r0.target")
    node1.wait_until_succeeds("test $(drbdadm cstate r0 | grep -c Connected) -ge 2")
    node1.succeed("drbdadm new-current-uuid --clear-bitmap r0/0")

    # R1 — the generator is registered.
    for m in disk_nodes:
        m.succeed("test -x /etc/systemd/system-generators/podman-system-generator")

    # R2 + R5 — INSTALL, on every node. Units are node-local (/run is not replicated), so a
    # survivor can only start the pod if it was rendered there too. This is the same shape the
    # payload image already has: warmed on every node, identity pinned on the volume.
    for m in disk_nodes:
        m.succeed("podman load -i ${imgA}")
        m.succeed("podman load -i ${imgB}")
        m.succeed("mkdir -p /run/containers/systemd")
        m.succeed("cp ${quadletUnits}/* /run/containers/systemd/")
        m.succeed("systemctl daemon-reload")

    # R2 — real units, generated at RUNTIME from files written after boot. This is the claim
    # a runtime install rests on: no OS switch, no Nix, no rebuild.
    for m in disk_nodes:
        m.succeed("systemctl cat spikepod-pod.service")
        m.succeed("systemctl cat spike-a.service")
        m.succeed("systemctl cat spike-b.service")
    print(node1.succeed("systemctl cat spikepod-pod.service spike-a.service"))
    # Nothing may have auto-started: the promoter owns when a service runs.
    for m in disk_nodes:
        m.succeed("test $(systemctl is-active spike-a.service) != active")

    # R4 — the chain names quadlet-generated units. data -> subvolume -> pod -> members -> VIP.
    snippet = (
        "[[promoter]]\n"
        "[promoter.resources.r0]\n"
        'start = [ "briard-data.service", "briard-spike-data.service", '
        '"spikepod-pod.service", "spike-a.service", "spike-b.service", "briard-vip.service" ]\n'
    )
    for m in disk_nodes:
        m.succeed("rm -f /run/briard/drbd-reactor.d/briard.toml")
        m.succeed(f"install -D /dev/stdin /run/briard/drbd-reactor.d/briard.toml <<'SNIP'\n{snippet}SNIP")
        m.succeed("systemctl start drbd-reactor.service")

    def role(m):
        return m.execute("drbdadm role r0")[1].strip()

    node1.wait_until_succeeds("curl -fsS http://192.168.1.100:8080/healthz", timeout=120)
    primary = next(m for m in disk_nodes if role(m) == "Primary")
    survivor = next(m for m in disk_nodes if m != primary)
    print(f"primary={primary.name} survivor={survivor.name}")

    # R3 — both containers run, in one pod, sharing a network namespace: B reached A on
    # localhost. And each wrote into its own subdirectory of the one service subvolume.
    print(primary.succeed("podman pod ps; podman ps --format '{{.Names}} {{.Pod}} {{.Status}}'"))
    primary.succeed("test $(systemctl is-active spike-a.service) = active")
    primary.succeed("test $(systemctl is-active spike-b.service) = active")
    primary.wait_until_succeeds("grep -q ok /var/lib/briard/spike/b/peer", timeout=60)
    print("pod members share a netns: B reached A over localhost")

    # R6 — ONE snapshot of the service subvolume captures both containers' data, which is what
    # makes a multi-container service a single {code + data} rollback unit.
    primary.wait_until_succeeds("test -f /var/lib/briard/spike/a/state.json", timeout=60)
    primary.succeed("btrfs subvolume snapshot -r /var/lib/briard/spike /var/lib/briard/.snapshots/spike-1")
    primary.succeed("test -f /var/lib/briard/.snapshots/spike-1/a/state.json")
    primary.succeed("grep -q ok /var/lib/briard/.snapshots/spike-1/b/peer")
    print("one snapshot captured both containers' data — a single rollback unit")

    # R5 — failover. The survivor runs the same pod, from units rendered on it at install time,
    # with the service's data intact across the takeover.
    # A margin first: "data intact" compared against a single tick would pass on a volume that
    # had been wiped and restarted, which is no assertion at all.
    primary.wait_until_succeeds(
        "test $(cat /var/lib/briard/spike/a/state.json | tr -cd 0-9) -ge 5", timeout=60
    )
    ticks_before = int(primary.succeed("cat /var/lib/briard/spike/a/state.json | tr -cd 0-9"))
    primary.crash()
    survivor.wait_until_succeeds("curl -fsS http://192.168.1.100:8080/healthz", timeout=120)
    survivor.succeed("test $(systemctl is-active spike-b.service) = active")
    ticks_after = int(survivor.succeed("cat /var/lib/briard/spike/a/state.json | tr -cd 0-9"))
    assert ticks_after >= ticks_before, f"data rewound across failover ({ticks_before} -> {ticks_after})"
    print(f"survivor runs the same pod, data intact ({ticks_before} -> {ticks_after})")
  '';
}
