package host

import (
	"crypto/rand"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"briard.io/shared/atomicfile"
	"briard.io/shared/flockname"
)

// THE THREE IDENTIFIERS, AND WHY THE AGENT MINTS THEM ([B.157]).
//
// One job each, and the property the split buys is that a NAME is a label while an IDENTITY is an
// id -- so renaming what humans see never touches the MAC, the DHCP client-id or the DRBD metadata.
// A rename never moves the address.
//
//	node id     node-scoped,  hidden   DRBD `on <name>`, guest hostname, the VM UUID, the cloud key
//	flock id    flock-scoped, hidden   the service MAC -> the DHCP client-id -> THE LEASE
//	flock name  flock-scoped, VISIBLE  mDNS `briard-<name>.local`, and the dashboard's URL
//
// install.sh minted them and wrote the values into config.env, which meant the installer owned
// three decisions it had no part in: two random draws and a word list that lives in this binary
// anyway (it already shelled out to `briard-agent --mint-flock-name` for the third, which is the
// shape of the mistake in one line -- the agent did the work and the shell owned the file).
//
// ⚠️ THEY ARE PET, and that is the whole care this file needs. DRBD writes `on <name>` into the
// resource and matches it against the running hostname, so a node id regenerated by a cattle
// reinstall leaves the guest unable to recognise its OWN metadata on the pet volume it just kept.
// Minting happens once, on a node that has never minted; after that these files are the answer.
//
// And it is Go rather than shell for the reason every move in [B.157] is: a Windows host needs
// exactly this and can reuse none of a POSIX script.

// defaultNodeName is what a node with no id of its own answers to: the literal every install had
// before [V3.20] gave each one its own. It survives as the LAST resort under the environment and
// the record, and as the value mintIdentity replaces.
const defaultNodeName = "guest"

const (
	nodeIDName    = "node-id"
	flockIDName   = "flock-id"
	flockNameName = "flock-name"
)

// identity is what this node calls itself. Empty fields are ones nobody has answered yet.
type identity struct {
	node, flockID, flockName string
}

// recordedIdentity reads the three records out of the node's pet state dir.
//
// A FREE FUNCTION over the directory rather than a method on Config, because the node id is needed
// BEFORE a Config exists: it names the DRBD self-peer, so ConfigFromEnv has to know it while it is
// still assembling the struct.
//
// A missing or unreadable file is an empty field, which is a node that has not minted yet -- never
// an error. Whitespace is trimmed because these files end in a newline by construction.
func recordedIdentity(dir string) identity {
	read := func(name string) string {
		b, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return ""
		}
		return strings.TrimSpace(string(b))
	}
	return identity{node: read(nodeIDName), flockID: read(flockIDName), flockName: read(flockNameName)}
}

// mintIdentity gives this node the identifiers it does not have, once, and records them.
//
// ⚠️ A NODE SOMEBODY ELSE HAS NAMED IS NEVER GIVEN ONE, and that single predicate is the whole
// guard -- the same one the subnet draw uses (subnets.go). NODE in the environment means a harness
// owns this node's identity, and minting a flock id beside it would hand every rig a random
// service MAC and a random mDNS name where today it has neither. So being told the node id means
// being told all three: nothing is minted, and the two that were empty stay empty, which is what
// `orNode` and "publish nothing" already read correctly.
//
// Errors are fatal to the call, not swallowed: a node that cannot write down who it is would mint
// a DIFFERENT id at the next boot and lose its own DRBD metadata. Better to refuse and say so.
func (cfg Config) mintIdentity(logf func(string, ...any)) (Config, error) {
	if os.Getenv("NODE") != "" {
		return cfg, nil
	}
	dir := cfg.stateDir()
	if dir == "" {
		return cfg, nil // no pet state: a hand-run agent or a unit test, with nowhere to record
	}
	id := recordedIdentity(dir)
	mint := func(name, have string, gen func() (string, error), mode os.FileMode, say string) (string, error) {
		if have != "" {
			return have, nil
		}
		v, err := gen()
		if err != nil {
			return "", fmt.Errorf("minting this node's %s: %w", name, err)
		}
		if err := atomicfile.Write(filepath.Join(dir, name), []byte(v+"\n"), mode, 0o700); err != nil {
			return "", fmt.Errorf("recording this node's %s: %w", name, err)
		}
		logf("%s", fmt.Sprintf(say, v, filepath.Join(dir, name)))
		return v, nil
	}
	var err error
	// 0600 on the two hidden ones and 0644 on the visible one: the flock name is a public label --
	// it is on the wire as an mDNS record the moment the guest comes up -- while the ids are the
	// node's own business.
	if id.node, err = mint(nodeIDName, id.node, newNodeID, 0o600,
		"identity: this machine is %s (recorded at %s -- keep this file; the replicated disk is keyed to it)"); err != nil {
		return cfg, err
	}
	if id.flockID, err = mint(flockIDName, id.flockID, newFlockID, 0o600,
		"identity: this home's id is recorded at %[2]s -- keep this file to keep your address"); err != nil {
		return cfg, err
	}
	if id.flockName, err = mint(flockNameName, id.flockName, flockname.Generate, 0o644,
		"identity: this install is called %s -- that is the name it answers to on your network (%s)"); err != nil {
		return cfg, err
	}
	return cfg.applyIdentity(id), nil
}

// applyIdentity fills only what is still empty, so the environment and the config file keep
// winning over a record exactly as they do everywhere else.
func (cfg Config) applyIdentity(id identity) Config {
	if cfg.Node == "" || cfg.Node == defaultNodeName {
		if id.node != "" {
			cfg.Node = id.node
		}
	}
	if cfg.FlockID == "" {
		cfg.FlockID = id.flockID
	}
	if cfg.FlockName == "" {
		cfg.FlockName = id.flockName
	}
	return cfg
}

// stateDir is the node's pet state dir, derived from ASSIGNMENT_CACHE's directory -- the same
// derivation the LAN record and the subnet record use, so a harness that points one elsewhere
// moves all of them together and is told twice about nothing.
func (cfg Config) stateDir() string {
	if cfg.AssignmentCache == "" {
		return ""
	}
	return filepath.Dir(cfg.AssignmentCache)
}

// newNodeID is `briard-node-<6 hex>`: readable in a journal, opaque in a database (the cloud keys
// on the bare `3f9a2c`).
//
// ⚠️ NOT DERIVED FROM ANYTHING. Not the hostname -- the household renames their desktop. Not the
// MAC -- that is the flock id's job, and this must stay node-scoped. Not the login name: [V3.19d]
// measured what leaking that onto a LAN looks like.
func newNodeID() (string, error) {
	var b [3]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	return fmt.Sprintf("briard-node-%x", b), nil
}

// newFlockID is a random UUID (version 4). The VIP's MAC derives from it (deriveMAC), so keeping
// the file is what keeps this node's address across a reinstall -- and, once pairing carries it,
// across a failover to a second node.
//
// Random rather than derived, unlike deriveUUID's name-based one beside it: a flock's id must not
// be reconstructible from anything a second install could also compute, or two houses would share
// a service MAC.
func newFlockID() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	b[6] = (b[6] & 0x0f) | 0x40 // version 4: random
	b[8] = (b[8] & 0x3f) | 0x80 // RFC 4122 variant
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16]), nil
}
